### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by aunamedia** [yaguilae/curso-html#1]
* Nota: Aprende a buscar documentación para conocer mejor las etiquetas y sus atributos... a través de Internet.  Dos buenos referentes de páginas para documentación HTML son w3scholl y developer.mozilla.org (para que los identifiques en google cuando los veas).  Éste último tiene mucha documentación en español.  Y el ambos tienen herramientas para probar el código y ver el resultado
* Nota2: Esto está siendo escrito en MarkDown, que es el leguaje que se está usando para este tipo de documentación (como el README.md).  Tiene un mini editor de texto para poder poner formatos básicos como negritas, y cosas así.
* Nota3: Crea un fichero con la práctica mencionada abajo, y súbelo al repositorio.

# Tabla (`table`)

Crea una tabla de 4 columnas con 3 filas.  Añádele una cabecera con `thead `y que el cuerpo esté en el `tbody`.  Añade de paso un pie con `tfoot`.  Te recuerdo que verás también etiquetas como: tr, td, th, además de las mencionadas: table, thead, tbody y tfoot.

Con un poco de conocimiento de CSS puedes ver las posibilidades de otra etiqueta de agrupación de columnas para unificar estilos: `colgroup `y `col ` Aunque no son etiquetas muy usadas.  Pero podrías ver ejemplos para completar el uso de tablas.

**Comment by aunamedia** [comment]
Hola Yola, esto es un comentario de esta ISSUE, donde podemos comentar cosas acerca de esta tarea o Issue, que como verás, la he completado con cosas como: Asignada a ti, etiqueta prácticas, un HITO a alcanzar llamado "practicas HTML", y todo eso después de haber creado la Issue con su título y su contenido en markdown.  Aquí mismo aparece un historial de cambios de la Issue.

Espero que disfrutes del viaje, ya que estás yendo por buen camino que muchos otros profesionales de la industria, solo conocen de oídas y nunca han usado (como en este caso, GitHub).

### Bienvenida a los Issues!

`Nota: Esto también está escrito en markdown y tú misma puedes ver cómo es y cómo escribes y cómo queda al previsualizarlo.`

**Comment by aunamedia** [comment]
Me refería a que escribieses en esta mismo idsue, no en otra. Y que me nombraras. 

Aquí es donde debes indicar que ya lo has hecho (a nivel comunicativo) ya que a nivel de git están los commits. 

En este caso has subido un comit con el fichero creado y otro con el fichero supuestamente terminado. Pero te diría que realizaras las siguientes correcciones:

- Que posea un título (h1) como todos los demás
- Que la tabla estuviera correcta. Ya que veo que cojean las cantidades de celdas según en qué filas.

**Comment by yaguilae** [comment]
vale lo he entendido

**Comment by yaguilae** [comment]
Ya está rectificado
