### ISSUE TITLE
HTML - Formularios

### ISSUE THREAD

**Issue by aunamedia** [yaguilae/curso-html#7]
Trabajar con formuarios de HTML

**Comment by aunamedia** [comment]
# Crea un formulario
#### Como ayuda, te indico que usarás las siguientes etiquetas (y los atibutos los valoras tú misma, identificando siempre que uses uno el motivo de por qué lo usas:
- form
- input

Los motivos de que exista un formulario en una página web, normalmente está dividido en dos:  Un comportamiento específico que se maneja desde un Script, o bien la posibilidad de dejar un mensaje a alguien o en algún sitio.  Ninguno de estos motivos te toca ahora ver, ya que antiguamente un formulario se podría enviar por correo electrónico mediante una acción llamada "mailto", pero dependía de que el usuario tuviese un cliente de correo como Outlook configurado, cosa que hoy en día no se ve, y por lo tanto, requiere de programación por parte del servidor para que puede enviarse dicho correo mediante una cuenta propia de la página web, o bien porque sea un mensaje que va a una base de datos, como podría ser por ejemplo, un foro, o incluso esto mismo que estoy escribiendo.  Como te decía, ninguna de estas dos opciones mencionadas te compete ahora el conocerlas, ya que estás en una etapa muy temprana, por lo que el principal objetivo de esta práctica es, saber construir un formulario, ya luego se verá qué se hace con él, o incluso una de las fases muy importantes en los formularios: "la validación" para confirmar que todo está correcto antes de enviarse, y eso tampoco te compete ahora.  Relájate y disfruta de "diseñar" tu formulario.

### Tarea
Crea un formulario como podríamos decir... "bien hecho".  Con esto quiero decir que siempre se puede hacer un formulario con los elementos mínimos para que funcione, que básicamente son la etiqueta "form" y los "imput"s y ya está.  Por lo que para esta práctica, intenta lucirte en tu formulario con todos los adornos que vayas conociendo, como los "label" por ejemplo, o cualquier atibuto que consideres interesante.  También están los fieldset, los leyend, etc. que van en esa línea de "adornos".  Te recuerdo que estamos exclusivamente con HTML y no con Diseño, por lo que debes conformarte con el cómo te lo muestra el navegador por defecto.  Ya entraremos en etapas de que puedas elegir la apariencia que desees, o que incluso uses recursos externos hechos por otras personas pala "lucir" tus elementos y tu formulario, como podría ser en este caso "Bootstrap" (que posee botones, colores, iconos, etc.).  Como te estoy mencionando elementos que "adornen" el formulario, en esta librería Bootstrap te encontrarás más elementos si cabe que lo adornan.  Uno de los atributos HTML que puedes usar en los imputs son los "placeholder" que ya verás para qué sirven.

### Formulario
El formulario que vas a crear debe tener el siguiente contenido:

Datos personales:
- Nombre
- Apellidos
- Email
- contraseña (imput type password)
- Edad (input numérico) 
- Sexo (input type radio) (hombre o mujer)
- Intereses (input type checkbox) (poner varios intereses)
- campo oculto llamado "tipo" con valor "web" (input hidden)

Trabajo:
- Sueldo: (select con 5 opciones) (de 0-800, de 801-1000, de 1001-1200, de 1201-1500, más de 1501) 
- Descripción de tu puesto: (textarea)

Acciones: 
- Botón Enviar (submit)
- Botón resetear (reset)
- Botón alternativo (button que no hace nada)

**Comment by yaguilae** [comment]
Realizado todas las etiquetas añadiendo input files, input image, algunos atributos como disable, autofocus, y algunas más, me quedaria repetir yo sola otro formulario.

**Comment by yaguilae** [comment]
Añadimos la etiqueta optgroup

**Comment by yaguilae** [comment]
He creado nuevo fichero con las etiquetas básicas descritas en la tarea y alguna adicional, en el fichero form hay comentarios de nuevas etiquetas vistas que no están descritas en en el ejercicio.
