### ISSUE TITLE
HTML 5 semántico

### ISSUE THREAD

**Issue by aunamedia** [yaguilae/curso-html#8]
Montar una página web de 3 páginas con un "rollo semántico" de HTML5

**Comment by aunamedia** [comment]
# Tarea HTML5 semántico

Se trata de crear por último una página web (olvidando el diseño de momento) con contenido estructurado en etiquetas HTML semántico, con la gama de etiquetas nuevas que salieron para definir el significado de las distintas partes de una web.  Es decir, el desarrollo tradicional hacía que un maquetador montara dos DIV uno para un menú y otro para un Artículo.  El objetivo de HTML5 es sustituir las etiquetas DIV por otras etiquetas es especifiquen mejor su función.  Como por ejemplo las etiqeutas NAV y ARTICLE en estos casos que he mencionado respectivamente.  Los motivos y ventajas para que esto sea así, no los vamos a tratar aquí ahora pero al menos recuerda que esas ventajas no las vas a ver con tus ojos, puesto que la semántica, normalmente es inapreciable.

Puedes consultar páginas a tu gusto sobre HTML5 y esas nuevas etiquetas (HEADER, ARTICLE, HGROUP, NAV, SECTION, ASIDE, FOOTER, etc.)

Te pongo páginas de ejemplo de lectura rápida que puedes leer por encima antes de hacer el ejercicio.
- https://www.arumeinformatica.es/blog/html5-nuevas-etiquetas-semanticas-y-estructurales/2
- https://desarrolloweb.com/articulos/etiquetas-semanticas-html5.html
- ... otras que tú busques.  Intenta leer rápido y varias antes de perder mucho tiempo en una.

- Podrías echar un ojo a esta página que habla de las "nuevas" etiquetas HTML5, que habla de las semánticas, y luego nombra otras más (otros tipos de informaciones) al final del artículo.  Curiosamente es el artículo que precede al último enlace que te he puesto: https://desarrolloweb.com/articulos/nuevas-etiquetas-html5.html

### Descripción de la tarea
Crea una página web que esté dividida en tres páginas, enlazadas entre sí mediante un menú, de una temática que tú elijas.  Intenta que tenga todos estas etiquetas que has visto en los enlaces que son Etiquetas Semánticas, y mira bien su función, por ejempo, NAV para un menú de Navegación, y no es para un título.  Intenta que las use todas, y a la vez intenta que tus páginas no tengan ningún DIV a no ser que lo consideres necesario.

Te propongo un tema "Colorea" pero puedes elegir otro (como animales, trabajo, ocio, o lo que desees) pero intenta que sea un tema que tenga noticias, artículos, secciones, etc.  Recuerda que las páginas deben ser diferentes, pero pueden tener un elemento en común como títulos (o parte de ellos) o los menús.  Y la estructura de las etiquetas también podrían ser idénticas, aunque cambie sus cantidades y su contenido.  No le dediques a esto mucho tiempo ya que son solo 3 páginas.  Y será tu última práctica de HTML.

## ¡ SUERTE !

**Comment by yaguilae** [comment]
Ejercicio completado
