### ISSUE TITLE
GIT y GITHUB Básico

### ISSUE THREAD

**Issue by aunamedia** [yaguilae/curso-html#9]
Conocer qué es GIT, montar un repositorio y darte de alta en Github.com y crear un repositorio, para poder crear commits en local y subirlos cada día que vayas trabajando en él.  En este caso, con las prácticas de HTML-CSS-JS

**Comment by yaguilae** [comment]
Creado el repositorio GIT en local con la rama master que es la que crea por defecto, mientras que en Github se ha creado con la rama main que e la crea por defecto desde octubre de 2020.
